## 配置服务器信息
server:
  port: 8000
  tomcat:
    uri-encoding: utf-8
  session:
    cookie:
      http-only: true
    
spring:
  profiles: 
    active: @profileActive@
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: false
